### ISSUE TITLE
GUI glitches when hovering over buttons and other elements

### ISSUE THREAD

**Issue by cgassmann** [Codectory/AutoActions#69]
GUI buttons and other elements are rendered incorrectly after hovering over them. Buttons seem to expand beyond the size of their intended area and become invisible. After switching between tabs, they are rendered correctly.

**Steps to reproduce the behavior:**
See screen recording:
https://user-images.githubusercontent.com/3438845/145710117-cacc06db-296f-47d9-976e-21b24f7c7e1d.mp4

**Desktop:**
OS: Windows 11 Pro
OS build: 22000.348

**Hardware:**
- Monitor: Dell S2721QS
- Graphics card: Dell Nvidia GeForce RTX 2070 SUPER
- Graphics card driver: 472.12

**Comment by Codectory** [comment]
Strange behavior. Are you using 100% scaling?

Christian ***@***.***> schrieb am So. 12. Dez. 2021 um 12:21:

**Comment by cgassmann** [comment]
Resolution is 4K (3840x2160), scaling is 150%.

**Comment by Codectory** [comment]
I cannot replicate this issue. Can you check if its gone when you set scaling to 100%?

**Comment by cgassmann** [comment]
Scaling doesn't seem to be the cause. The issue also happens at 100%.

**Comment by Codectory** [comment]
Do you still have this issue?

**Comment by cgassmann** [comment]
Still happens for buttons like "Info" and "Logs" on the 1st tab, or "Launch application" on the 3rd tab, but not e.g. for checkboxes on the last tab anymore.

**Comment by cgassmann** [comment]
Resolved with latest version... 👍
