### ISSUE TITLE
Settings not saving on startup

### ISSUE THREAD

**Issue by xreyuk** [Codectory/AutoActions#85]
I have set AutoHDR to run on startup, however it's starting up with completely new blank settings and I have to restore the backup file.

Any suggestions?

**Comment by Codectory** [comment]
Can you send me the backup file?

**Comment by xreyuk** [comment]
[UserSettings.json.txt](https://github.com/Codectory/AutoHDR/files/7824182/UserSettings.json.txt)

This is the latest file I restored at boot. It was the backup and I renamed it and deleted the new usersettings.json the application generated.

This was using the latest version that was released today

**Comment by Codectory** [comment]
I cannot reproduce is with this settings file. It's loading without any problems.

**Comment by xreyuk** [comment]
So it will load without issue when i've booted into windows, but if i restart, and try to load the application again, it doesn't load and makes a new blank settings file. When I delete the new blank settings file, and change the backup to UserSettings.json - it loads fine.

Is there anything I could do to show you logs or maybe I have something setup wrong?

**Comment by Codectory** [comment]
Yeah, enable logging in the settings. You can send me the logfile then.

xreyuk ***@***.***> schrieb am Fr. 7. Jan. 2022 um 18:09:

**Comment by xreyuk** [comment]
So I can't provide a log file, cause it doesn't generate one when the app tries to boot on windows startup, because the app loads with default settings.

It literally only happens when the app tries to start on startup, if I start the application manually it loads the settings file fine, however if I try to either enable auto start within the application, or even add it manually as a windows startup application it generates a blank settings file.

Are there any other settings I have enabled which may be causing issues?

**Comment by xreyuk** [comment]
I think I may have figured out the issue. Upon startup my WiFi takes around 1 minute to connect, if the application is opened before I have internet connectivity (either by manual or automatic startup) it fails to load with the settings and generate a new settings file.  If I wait until the WiFi is connected and load it manually the application starts correctly with the correct settings.

This behaviour is the same whether I have 'check for new version on startup' checked or unchecked.

**Comment by Codectory** [comment]
Do you have added any apps to AutoHDR which are installed on a network drive?

**Comment by xreyuk** [comment]
I have no apps added to AutoHDR from a network drive, but I do have a network drive connected.

**Comment by Codectory** [comment]
Please check again with 1.9.5
