### ISSUE TITLE
Enhancement: auto-update option

### ISSUE THREAD

**Issue by SullieLore** [Codectory/AutoActions#93]
Hi,

I wasn't sure how to open an enhancement request, as it is blank in the report area. I'll try to edit this when posted.

There are quite a few updates happening, which is excellent to see since this is a useful project. However, it would be more efficient if the program had an auto-update option, instead of manually closing the app, overwriting, then opening the app again.

**Comment by Codectory** [comment]
Is already in the works

**Comment by Codectory** [comment]
See 1.9.12
