### ISSUE TITLE
Bitdefender flagging as malware

### ISSUE THREAD

**Issue by flowerdealer** [Codectory/AutoActions#95]
Ever since the autoupdate update, the software is being flagged as malware by Bitdefender. It might be just Bitdefender being Bitdefender, but just flagging.

**Comment by Codectory** [comment]
Do you have any screenshot or other data?

**Comment by flowerdealer** [comment]
![Screenshot 2022-01-20 093957](https://user-images.githubusercontent.com/810756/150392639-d9933cac-0377-495b-a73c-eb35e3e0f881.png)
![Screenshot 2022-01-20 094101](https://user-images.githubusercontent.com/810756/150392695-4e680d6c-e075-47af-9a84-981f2176e2b6.png)

**Comment by flowerdealer** [comment]
I've exempted it now and it's working fine, but just figured I'd flag it as whatever behaviour this is doing might happen to other people.

**Comment by Codectory** [comment]
Nothing I can really do. I need to ask every anti virus producer to whitelist AutoActinos.
