### ISSUE TITLE
Origin/Star Wars not activating automatically?

### ISSUE THREAD

**Issue by xNetrunner** [Codectory/AutoActions#99]
**Describe the bug**
Not working organically with origin games(?) or at least Star Wars Jedi: The Fallen Order.

**To Reproduce**
1. Add -any or all- Star Wars binaries as an application and select HDR profile in AutoActions. The one that it uses is actually `starwarsjedifallenorder.exe`
2. Go to 'Steam' and launch on 'Star Wars Jedi: Fallen Order'
3. No HDR enabled after game is done loading. 

**Note**
Compatibility mode does not seem to help.

**Expected behavior**
HDR to be enabled. Several other games I run don't have this problem.

**Comment by Codectory** [comment]
Could you send me a logfile of the time you started fallen order?
